### ISSUE TITLE
Action can get stuck if rustdoc changes behavior from one Rust version to another

### ISSUE THREAD

**Issue by scouten-adobe** [obi1kenobi/cargo-semver-checks-action#17] opened 2022-12-19 20:04 UTC
We've been struggling with [cargo-semver-checks-action erroring out] and blocking PR validations and release builds.

I think we've found a temporary workaround, but wanted you to be aware of the issue.

Please read the log at https://github.com/contentauth/c2pa-rs/actions/runs/3734139307/jobs/6335827121.

In this log, version 0.16.0 is the prior release for comparison and you'll notice that the `cargo rustdoc` task for _that_ release fails with:

```
error: unclosed HTML tag `u8`
   --> sdk/src/assertion.rs:175:58
175 | /// for Json assertions the data is a Json string and Vec<u8> for
                                                             ^^^^
```

… which is a valid error in Rust 1.66. However, at the time we released our crate 0.16.0, we were still on Rust 1.65 where the above doc comment went unnoticed.

The problem is that (short of disabling the cargo-semver-checks-action, which is how we're now working around it), the _previous_ build check can't pass and so the step fails.

Not sure how to work around this, but thought you should be aware of the issue.

**Comment by obi1kenobi** [comment] 2022-12-19 20:30
Thanks for the detailed report! Especially appreciate you digging into the cause — it really makes it easier to come up with a fix.

It seems that it's possible to override the `deny(warnings)` from the command line by setting `RUSTFLAGS=-Awarnings`: https://users.rust-lang.org/t/suppress-warnings-from-the-cargo-command/10536/2

However, I'm hesitant to enable that by default since my understanding is that any change to `RUSTFLAGS` causes a full rebuild, which could be quite expensive. And making the `RUSTFLAGS=-Awarnings` command opt-in as a config option seems suboptimal too, since it should remain off almost all of the time — except when a new lint comes up like this.

I could perhaps make the action attempt to build the baseline normally first, and then retry with `-Awarnings` if the first attempt failed.

How does that sound? Is there a better option? Any downsides I might be missing?

Two other, minor things:
- Re: disabling `cargo-semver-checks`, I think you'd only need to do that until your next version is released, right? After that, that version becomes the baseline, and the problem should go away. Please let me know if that doesn't end up being the case for any reason.
- Based on user feedback, we're planning some significant upgrades to the GitHub Action in the near future, aiming to significantly improve performance by using a prebuilt binary and caching baseline files. Is that something you also see as important, or is there something else you'd rather have first? Would you be interested in being an early adopter of the new faster Action and giving us feedback on it?

**Comment by obi1kenobi** [comment] 2023-02-11 04:12
Resolved by https://github.com/obi1kenobi/cargo-semver-checks/pull/357 and will be available with the next release.

**Closed by obi1kenobi** 2023-02-11 04:12 UTC
Labels: A-action, C-bug
