### ISSUE TITLE
Features add/remove support

### ISSUE THREAD

**Issue by ssrlive** [obi1kenobi/cargo-semver-checks-action#91] opened 2024-12-15 04:16 UTC
If a Feature of a crate is added or deleted, `cargo-semver-checks-action` cannot detect the version difference. I don't know if this is a bug.

**Comment by obi1kenobi** [comment] 2024-12-15 04:24
Hi! Could you elaborate on what you mean by "cannot detect the version difference"?

Ideally, a simple example that reproduces what you saw, and describes how it differs from what you expected would be perfect.

**Comment by ssrlive** [comment] 2024-12-15 04:31
Here is my changes to my crate. but `cargo-semver-checks-action` not warning me something changed.

![image](https://github.com/user-attachments/assets/cffbe640-1e73-4e57-9779-c8c5a249c7ca)

**Comment by obi1kenobi** [comment] 2024-12-15 04:41
That does indeed look suspect. Could you provide a complete repro example which demonstrates this behavior? For example, a link to the PR where you observed that (if the repo is public) or a new example project that demonstrates the issue otherwise?

Without a repro example, I'm not sure how I'd be able to look into this further.

**Comment by ssrlive** [comment] 2024-12-15 04:43
https://github.com/tun2proxy/socks5-impl/actions/runs/12330183394/job/34415347036

```
Run obi1kenobi/cargo-semver-checks-action@v2
  with:
    verbose: false
    rust-toolchain: stable
    github-token: ***
  env:
    CARGO_TERM_COLOR: always
    CARGO_HOME: /home/runner/.cargo
    CARGO_INCREMENTAL: 0
/home/runner/.cargo/bin/rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/runner/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.83.0 (90b35a6[2](https://github.com/tun2proxy/socks5-impl/actions/runs/12330183394/job/34415347036#step:4:2)3 2024-11-26)
/home/runner/.cargo/bin/rustup set profile minimal
info: profile set to 'minimal'
/home/runner/.cargo/bin/rustup toolchain install stable
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.8[3](https://github.com/tun2proxy/socks5-impl/actions/runs/12330183394/job/34415347036#step:4:3).0 (90b35a623 202[4](https://github.com/tun2proxy/socks5-impl/actions/runs/12330183394/job/34415347036#step:4:4)-11-26)

info: checking for self-update
warning: tool `rust-analyzer` is already installed, remove it from `/home/runner/.cargo/bin`, then run `rustup update` to have rustup manage this tool.
warning: tool `rustfmt` is already installed, remove it from `/home/runner/.cargo/bin`, then run `rustup update` to have rustup manage this tool.
warning: tool `cargo-fmt` is already installed, remove it from `/home/runner/.cargo/bin`, then run `rustup update` to have rustup manage this tool.
/home/runner/.cargo/bin/rustc --version
rustc 1.83.0 (90b3[5](https://github.com/tun2proxy/socks5-impl/actions/runs/12330183394/job/34415347036#step:4:5)a623 2024-11-26)
cargo-semver-checks is not installed, installing now...
downloading cargo-semver-checks from https://api.github.com/repos/obi1kenobi/cargo-semver-checks/releases/assets/212[6](https://github.com/tun2proxy/socks5-impl/actions/runs/12330183394/job/34415347036#step:4:6)73625
extracting /home/runner/work/_temp/2aec5685-3ebd-4335-984f-ff4a04ee3c2c
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/ae[7](https://github.com/tun2proxy/socks5-impl/actions/runs/12330183394/job/34415347036#step:4:7)13d20-1990-479c-bc3f-63c1e5[8](https://github.com/tun2proxy/socks5-impl/actions/runs/12330183394/job/34415347036#step:4:8)ac161 -f /home/runner/work/_temp/2aec5685-3ebd-4335-[9](https://github.com/tun2proxy/socks5-impl/actions/runs/12330183394/job/34415347036#step:4:9)84f-ff4a04ee3c2c
Restoring rustdoc cache...
Rustdoc cache path: /home/runner/work/socks5-impl/socks5-impl/semver-checks/target/semver-checks/cache.
/home/runner/.cargo/bin/rustc --version
rustc 1.83.0 (90b35a623 2024-11-26)
/home/runner/.cargo/bin/cargo semver-checks --version
cargo-semver-checks 0.38.0
Rustdoc cache key: semver-semver-93c4e40f0b737772-linux-rustc-1.83.0-(90b35a623-2024-11-26)-cargo-semver-checks-0.38.0-d41d8cd98f00b204e9800998ecf8427e-semver-checks-rustdoc.
Received 149663 of 149663 ([10](https://github.com/tun2proxy/socks5-impl/actions/runs/12330183394/job/34415347036#step:4:11)0.0%), 5.3 MBs/sec
Cache Size: ~0 MB (149663 B)
/usr/bin/tar -xf /home/runner/work/_temp/99687dad-f886-49f0-8427-e2acad0cbd89/cache.tzst -P -C /home/runner/work/socks5-impl/socks5-impl --use-compress-program unzstd
Cache restored successfully
Restored rustdoc cache using key semver-semver-93c4e40f0b737772-linux-rustc-1.83.0-(90b35a623-2024-[11](https://github.com/tun2proxy/socks5-impl/actions/runs/12330183394/job/34415347036#step:4:12)-26)-cargo-semver-checks-0.38.0-d41d8cd98f00b204e9800998ecf8427e-semver-checks-rustdoc-09361e52290035ca90438a688be5b9ca22255eff.
/home/runner/.cargo/bin/cargo semver-checks check-release
    Building socks5-impl v0.5.17 (current)
       Built [  11.534s] (current)
     Parsing socks5-impl v0.5.17 (current)
      Parsed [   0.0[12](https://github.com/tun2proxy/socks5-impl/actions/runs/12330183394/job/34415347036#step:4:13)s] (current)
     Parsing socks5-impl v0.5.17 (baseline, cached)
      Parsed [   0.011s] (baseline)
    Checking socks5-impl v0.5.17 -> v0.5.17 (no change)
     Checked [   0.031s] 107 checks: 107 pass, 0 skip
     Summary no semver update required
    Finished [  12.030s] socks5-impl
Rustdoc cache is up to date, skipping saving.
```

**Comment by obi1kenobi** [comment] 2024-12-15 04:54
Thanks! After reviewing this, we don't actually have a lint for this yet so the cargo-semver-checks output is what was expected to happen here.

Hopefully a future edition of cargo-semver-checks will include a lint for this. We don't have a tracking issue for adding this lint specifically, but if it would be useful to you, I'd be happy to make one. In the meantime, I'll close this issue since it's in the actions repo, and it isn't actionable since this isn't an actions-related problem.

Thanks for reporting this!

**Closed by obi1kenobi** 2024-12-15 04:54 UTC

**Comment by obi1kenobi** [comment] 2024-12-17 00:37
This `cargo-semver-checks` PR adds the lint you requested, so it should be available in future releases:
https://github.com/obi1kenobi/cargo-semver-checks/pull/1051

**Comment by ssrlive** [comment] 2024-12-17 02:36
Thanks.
